version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    container_name: database
    ports:
      - "5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

